# Generated by Django 4.2 on 2023-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movieorder_movie_movie_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
